//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Android_DataBaseEntities : DbContext
    {
        public Android_DataBaseEntities()
            : base("name=Android_DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Fletes_Vista_Fletes_Tarifas_Result> Fletes_Vista_Fletes_Tarifas(string tipo, Nullable<int> codigoProyectoOrigen, Nullable<int> codigoProyectoDestino)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var codigoProyectoOrigenParameter = codigoProyectoOrigen.HasValue ?
                new ObjectParameter("CodigoProyectoOrigen", codigoProyectoOrigen) :
                new ObjectParameter("CodigoProyectoOrigen", typeof(int));
    
            var codigoProyectoDestinoParameter = codigoProyectoDestino.HasValue ?
                new ObjectParameter("CodigoProyectoDestino", codigoProyectoDestino) :
                new ObjectParameter("CodigoProyectoDestino", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fletes_Vista_Fletes_Tarifas_Result>("Fletes_Vista_Fletes_Tarifas", tipoParameter, codigoProyectoOrigenParameter, codigoProyectoDestinoParameter);
        }
    }
}
