//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteMvc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarreraEntities : DbContext
    {
        public BarreraEntities()
            : base("name=BarreraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Equipo_Proyecto> Equipo_Proyecto { get; set; }
        public virtual DbSet<Organigrama_Proyecto> Organigrama_Proyecto { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
       
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Tarea_Log> Tarea_Log { get; set; }
        public virtual DbSet<Tarea_Mensaje> Tarea_Mensaje { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
    }
}
