//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraPushMovil3
    {
        public string codbus { get; set; }
        public string dir { get; set; }
        public int CodigoPublicidad { get; set; }
        public string DescripcionPublicidad { get; set; }
        public string Medidas { get; set; }
        public string Contrato { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFIn { get; set; }
        public int CodigoContrato { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public byte[] Imagen { get; set; }
        public string CalendarioPeriodo { get; set; }
        public Nullable<System.DateTime> FechaEjecucion { get; set; }
        public Nullable<int> Semana { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> dia { get; set; }
        public Nullable<int> codigoZona { get; set; }
        public int id { get; set; }
    }
}
