//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteMvc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PublicidadEntities_ : DbContext
    {
        public PublicidadEntities_()
            : base("name=PublicidadEntities_")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Imagen> Imagen { get; set; }
        public virtual DbSet<Problema_Visita> Problema_Visita { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Proyectos_Ubicaciones> Proyectos_Ubicaciones { get; set; }
        public virtual DbSet<Supervisor> Supervisor { get; set; }
        public virtual DbSet<ContratoPago> ContratoPago { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
        public virtual DbSet<ZonaGeografica> ZonaGeografica { get; set; }
        public virtual DbSet<BitacoraPushMovil3> BitacoraPushMovil3 { get; set; }
        public virtual DbSet<Publicidad> Publicidad { get; set; }
    
        public virtual ObjectResult<VISTA_PRESUPUESTO_CONTRATO_Result> VISTA_PRESUPUESTO_CONTRATO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VISTA_PRESUPUESTO_CONTRATO_Result>("VISTA_PRESUPUESTO_CONTRATO");
        }
    }
}
