//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo_Proyecto
    {
        public int Id { get; set; }
        public string Codigo_Puesto { get; set; }
        public Nullable<int> ReportID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Codigo_Empleado { get; set; }
        public Nullable<int> Codigo_Proyecto { get; set; }
        public string Designacion { get; set; }
        public Nullable<int> Codigo_Empresa { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
