//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publicidad()
        {
            this.Visita = new HashSet<Visita>();
        }
    
        public int CodigoPublicidad { get; set; }
        public string Descripcion { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Estado { get; set; }
        public Nullable<int> CodigoProyecto { get; set; }
        public Nullable<int> CodigoContrato { get; set; }
        public string Alto { get; set; }
        public string Ancho { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FechaCambioImagen { get; set; }
        public byte[] imagen { get; set; }
        public string Demo { get; set; }
        public Nullable<int> CodigoZona { get; set; }
        public string CodigoBusqueda { get; set; }
        public string Calendario_Periodo { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Proyectos_Ubicaciones Proyectos_Ubicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visita> Visita { get; set; }
        public virtual ZonaGeografica ZonaGeografica { get; set; }
    }
}
