//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visita()
        {
            this.Imagen1 = new HashSet<Imagen>();
        }
    
        public int Codigo { get; set; }
        public Nullable<int> Codigo_Publicidad { get; set; }
        public Nullable<int> Codigo_Problema { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> codSupervisor { get; set; }
        public Nullable<int> Codigo_Proyecto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public byte[] imagen { get; set; }
        public Nullable<int> Codigo_Visita { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagen> Imagen1 { get; set; }
        public virtual Problema_Visita Problema_Visita { get; set; }
        public virtual Supervisor Supervisor { get; set; }
        public virtual Publicidad Publicidad { get; set; }
    }
}
